notifications:
  email: false

language: node_js
node_js:
  - 9
  - 8

services:
  - docker

addons:
  apt:
    packages:
      # See https://github.com/atom/ci
      - libsecret-1-dev

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/

install:
  # Retry install on fail to avoid failing a build on network/disk/external errors
  - travis_retry npm install
  # See https://github.com/atom/ci
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh
  # Add apm to the PATH
  - export PATH=$PATH:~/atom/usr/bin

script:
  - npm run test

after_success:
  - npm run codecov
  - npm run semantic-release
